[package]
name = "skarmory"
version = "0.1.0"
edition = "2021"

[dependencies]
scraper = "0.21.0"

[dependencies.tokio]
version = "1.4.11"
features = ["rt-multi-thread", "time"]

[dependencies.axum]
version = "0.7.8"
fetures = ["json"]
